server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://8.134.152.53:3306/gm?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: Tj%&2*hq^aAvUrc!

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

sa-token:
  token-name: satoken
  timeout: 86400
  is-log: false

